services:
  znuny:
    container_name: znuny
    build: ./build
    restart: no
    environment:
      - TZ=Europe/Budapest
    env_file:
      - .env
    ports:
      - 8080:80
    volumes:
      - db:/var/lib/mysql
      - kernel:/opt/znuny/Kernel
      - /etc/localtime:/etc/localtime:ro

volumes:
  db:
  kernel:
