services:
  znuny:
    container_name: znuny
    build: ./build
    restart: no
    environment:
      - TZ=Europe/Budapest
    ports:
      - 8080:80
    volumes:
      - mariadb:/var/lib/mysql
      - znuny_kernel:/opt/znuny/Kernel
      - /etc/localtime:/etc/localtime:ro

volumes:
    mariadb:
    znuny_kernel:
